### ISSUE TITLE
panic: SOCKS5 listen failed: listen tcp 127.0.0.1:1080: bind: An attempt was made to access a socket in a way forbidden by its access permissions.

### ISSUE THREAD

**Issue by Geniucker** [Mythologyli/zju-connect#41]
**提交之前**

在提交报告之前，请确保：
+ 你正在使用 [Release](https://github.com/Mythologyli/zju-connect/releases) 中的最新版本
+ 如果你可以访问 CC98，请确保你已经阅读过以下说明：
    + [使用 ZJU Connect 代替 EasyConnect 提升你的 RVPN 体验](https://www.cc98.org/topic/5521873)
    + [端口转发、定时保活、自动选线、密码保存](https://www.cc98.org/topic/5570875)
+ 如果你可以访问 CC98 并且你的问题与配合 ZJU Rule 有关，请确保你已阅读过：
    + [使用 Clash+ZJU Rule](https://www.cc98.org/topic/5257184)
    + [Clash+ZJU Rule 的常见问题与解决方案](https://www.cc98.org/topic/5677200)
    + [ZJU Rule Github](https://github.com/Mythologyli/ZJU-Rule) 说明及 [Issues](https://github.com/Mythologyli/ZJU-Rule/issues?q=is%3Aissue)
+ 你已搜索过现有的 [Issues](https://github.com/Mythologyli/zju-connect/issues?q=is%3Aissue) 并且未发现重复

**确认无误后，请删除下方横线及以上内容。之后，请修改下方的模版并提交报告**

---

**软件版本**
zju connect v1.0.3自带的
我猜是v0.4.1

**使用环境**
Windows 11 x64
**服务端地址**
rvpn.zju.edu.cn:443

**故障描述** (建议结合图片说明)

日志里说
panic: SOCKS5 listen failed: listen tcp 127.0.0.1:1080: bind: An attempt was made to access a socket in a way forbidden by its access permissions.
http监听的端口有类似错误
然而我`netstat -ano | findstr "1080"`并没有发现被占用

**重现方法**
我也不知道如何重现，晚上一开始还是能连上的，突然就这样了，我等会儿重启一下逝逝

**预期行为**
正常连接

**日志**
```
Version: 1.0.3
Windows 11 Version 22H2
2023-09-30 22:31:42 工作模式设置为：RVPN
网络检测结果 | 默认 DNS 可用：是 | ZJU 校园网：是 | ZJU 内网 DNS 解析：是 | ZJUWLAN：否 | ZJUWLAN-Secure：否 | ZJU 有线网：否 | 互联网连接：是 | 是否启用代理：否
2023/09/30 22:31:45 Login Request: https://rvpn.zju.edu.cn:443/por/login_auth.csp?apiversion=1

2023/09/30 22:31:46 Twf Id: 93c5ea07d2f36ac5
2023/09/30 22:31:46 RSA Key: BA32A088AC812E30BFA52EEAB47B288F400DCDD44DD5E58D93BE79009B430BF7936251F1596BB9F874B27A49FC47F921EC5DDCD7FBBADED86032E4BE8E594C164EF3FC2FAB76B282544DF6173878AB493C5A69CCF1664C1CBDCAE79CEB6E2D8D0580F17CB11A9E829A489FE5288748DA9301DAF5BCACE0BA4CDF3BBD10C7BC670F6C9BD4A35581C8071E89A0DFDA471B43C2A4E2EF20955960B0A0C0E53D3A176BE80EED564F90557DC15732E757821F2934D60B804CE631105B11B5011E9407707B51D59C7CB0AB4A29BE3EB3CE542847622AB49D157AFE3FC8D86D210B548BB81E8CFF7819B42AAAD6B10B3737670230F369BBDBDAAAB332354FBE653F3381
2023/09/30 22:31:46 RSA Exp: 65537
2023/09/30 22:31:46 WARNING: No CSRF Code Match. Maybe you're connecting to an older server? Continue anyway...

2023/09/30 22:31:46 Login Request: https://rvpn.zju.edu.cn:443/por/login_psw.csp?anti_replay=1&encrypt=1&type=cs

2023/09/30 22:31:46 No NextAuth found.
2023/09/30 22:31:46 Web Login process done.

2023/09/30 22:31:46 ECAgent Request: /por/conf.csp & /por/rclist.csp

2023/09/30 22:31:46 Server Session ID: d1ac2926ac351964cc6e56221fb274c7ebd17ea1b784bca10f167d6b76cc7e4f

2023/09/30 22:31:46 Parsed /por/conf.csp 
2023/09/30 22:31:46 Testing 4 servers...

Ping tcp://218.108.88.254:443(218.108.88.254:443) - Connected - time=7.7295ms
Ping tcp://61.175.193.50:443(61.175.193.50:443) - Connected - time=7.7295ms

Ping tcp://61.175.193.50:443(61.175.193.50:443) - Connected - time=7.0612ms
Ping tcp://218.108.88.254:443(218.108.88.254:443) - Connected - time=7.0612ms

Ping tcp://210.32.174.2:443 - failed: dial tcp 210.32.174.2:443: i/o timeout
Ping tcp://124.160.105.200:443 - failed: dial tcp 124.160.105.200:443: i/o timeout

Ping tcp://218.108.88.254:443(218.108.88.254:443) - Connected - time=7.1601ms
Ping tcp://61.175.193.50:443(61.175.193.50:443) - Connected - time=7.1601ms

Ping tcp://124.160.105.200:443 - failed: dial tcp 124.160.105.200:443: i/o timeout

Ping tcp://210.32.174.2:443 - failed: dial tcp 210.32.174.2:443: i/o timeout

Ping tcp://124.160.105.200:443 - failed: dial tcp 124.160.105.200:443: i/o timeout
Ping tcp://210.32.174.2:443 - failed: dial tcp 210.32.174.2:443: i/o timeout

2023/09/30 22:31:49 Find best server: 218.108.88.254:443
2023/09/30 22:31:49 Login again...
2023/09/30 22:31:49 Login Request: https://218.108.88.254:443/por/login_auth.csp?apiversion=1

2023/09/30 22:31:49 Twf Id: e2cc811296bdf1ac
2023/09/30 22:31:49 RSA Key: BA32A088AC812E30BFA52EEAB47B288F400DCDD44DD5E58D93BE79009B430BF7936251F1596BB9F874B27A49FC47F921EC5DDCD7FBBADED86032E4BE8E594C164EF3FC2FAB76B282544DF6173878AB493C5A69CCF1664C1CBDCAE79CEB6E2D8D0580F17CB11A9E829A489FE5288748DA9301DAF5BCACE0BA4CDF3BBD10C7BC670F6C9BD4A35581C8071E89A0DFDA471B43C2A4E2EF20955960B0A0C0E53D3A176BE80EED564F90557DC15732E757821F2934D60B804CE631105B11B5011E9407707B51D59C7CB0AB4A29BE3EB3CE542847622AB49D157AFE3FC8D86D210B548BB81E8CFF7819B42AAAD6B10B3737670230F369BBDBDAAAB332354FBE653F3381
2023/09/30 22:31:49 RSA Exp: 65537
2023/09/30 22:31:49 WARNING: No CSRF Code Match. Maybe you're connecting to an older server? Continue anyway...

2023/09/30 22:31:49 Login Request: https://218.108.88.254:443/por/login_psw.csp?anti_replay=1&encrypt=1&type=cs

2023/09/30 22:31:49 No NextAuth found.
2023/09/30 22:31:49 Web Login process done.

2023/09/30 22:31:49 ECAgent Request: /por/conf.csp & /por/rclist.csp

2023/09/30 22:31:49 Server Session ID: 911af6279c455ac42a333e53a15c02bdf01da8c663d056c628414abdc1e87e3d

2023/09/30 22:31:49 Parsed /por/conf.csp 

2023/09/30 22:31:49 Parsed /por/rclist.csp 
2023/09/30 22:31:49 try parsing by goXml
2023/09/30 22:31:49 Progress: 0/100 (ResourceList.Rcs)

2023/09/30 22:31:49 Progress: 0/100 (ResourceList.Rcs)
2023/09/30 22:31:49 Super large rule detected for: 211.151.90.1-211.151.247.254 mask: 0
2023/09/30 22:31:49 Progress: 0/100 (ResourceList.Rcs)
2023/09/30 22:31:49 Progress: 1/100 (ResourceList.Rcs)
2023/09/30 22:31:49 Super large rule detected for: 10.0.0.1-10.190.64.9 mask: 0
2023/09/30 22:31:49 Super large rule detected for: 10.190.126.251-10.255.255.254 mask: 0
2023/09/30 22:31:49 Progress: 1/100 (ResourceList.Rcs)
2023/09/30 22:31:49 Progress: 1/100 (ResourceList.Rcs)
2023/09/30 22:31:49 Progress: 2/100 (ResourceList.Rcs)
2023/09/30 22:31:49 Progress: 2/100 (ResourceList.Rcs)
2023/09/30 22:31:49 Progress: 2/100 (ResourceList.Rcs)
2023/09/30 22:31:49 Progress: 3/100 (ResourceList.Rcs)
2023/09/30 22:31:49 Progress: 3/100 (ResourceList.Rcs)
2023/09/30 22:31:49 Progress: 3/100 (ResourceList.Rcs)
2023/09/30 22:31:49 Progress: 4/100 (ResourceList.Rcs)
2023/09/30 22:31:49 Progress: 4/100 (ResourceList.Rcs)
2023/09/30 22:31:49 Progress: 4/100 (ResourceList.Rcs)
2023/09/30 22:31:49 Progress: 5/100 (ResourceList.Rcs)
2023/09/30 22:31:49 Progress: 5/100 (ResourceList.Rcs)
2023/09/30 22:31:49 Progress: 5/100 (ResourceList.Rcs)
2023/09/30 22:31:49 Progress: 6/100 (ResourceList.Rcs)
2023/09/30 22:31:49 Progress: 6/100 (ResourceList.Rcs)
2023/09/30 22:31:49 Progress: 6/100 (ResourceList.Rcs)
2023/09/30 22:31:49 Progress: 7/100 (ResourceList.Rcs)
2023/09/30 22:31:49 Progress: 7/100 (ResourceList.Rcs)
2023/09/30 22:31:49 Progress: 7/100 (ResourceList.Rcs)
2023/09/30 22:31:49 Progress: 8/100 (ResourceList.Rcs)
2023/09/30 22:31:49 Progress: 8/100 (ResourceList.Rcs)
2023/09/30 22:31:49 Progress: 8/100 (ResourceList.Rcs)
2023/09/30 22:31:49 Progress: 9/100 (ResourceList.Rcs)
2023/09/30 22:31:49 Progress: 9/100 (ResourceList.Rcs)
2023/09/30 22:31:49 Progress: 10/100 (ResourceList.Rcs)
2023/09/30 22:31:49 Progress: 10/100 (ResourceList.Rcs)

2023/09/30 22:31:49 Progress: 10/100 (ResourceList.Rcs)
2023/09/30 22:31:49 Progress: 11/100 (ResourceList.Rcs)
2023/09/30 22:31:49 Progress: 11/100 (ResourceList.Rcs)
2023/09/30 22:31:49 Progress: 11/100 (ResourceList.Rcs)
2023/09/30 22:31:49 Progress: 12/100 (ResourceList.Rcs)
2023/09/30 22:31:49 Progress: 12/100 (ResourceList.Rcs)
2023/09/30 22:31:49 Progress: 12/100 (ResourceList.Rcs)
2023/09/30 22:31:49 Progress: 13/100 (ResourceList.Rcs)
2023/09/30 22:31:49 Progress: 13/100 (ResourceList.Rcs)
2023/09/30 22:31:49 Progress: 13/100 (ResourceList.Rcs)
2023/09/30 22:31:49 Progress: 14/100 (ResourceList.Rcs)
2023/09/30 22:31:49 Progress: 14/100 (ResourceList.Rcs)
2023/09/30 22:31:49 Progress: 14/100 (ResourceList.Rcs)
2023/09/30 22:31:49 Progress: 15/100 (ResourceList.Rcs)
2023/09/30 22:31:49 Progress: 15/100 (ResourceList.Rcs)
2023/09/30 22:31:49 Progress: 15/100 (ResourceList.Rcs)
2023/09/30 22:31:49 Progress: 16/100 (ResourceList.Rcs)
2023/09/30 22:31:49 Progress: 16/100 (ResourceList.Rcs)
2023/09/30 22:31:49 Progress: 16/100 (ResourceList.Rcs)
2023/09/30 22:31:49 Progress: 17/100 (ResourceList.Rcs)
2023/09/30 22:31:49 Progress: 17/100 (ResourceList.Rcs)
2023/09/30 22:31:49 Progress: 17/100 (ResourceList.Rcs)
2023/09/30 22:31:49 Progress: 18/100 (ResourceList.Rcs)
2023/09/30 22:31:49 Progress: 18/100 (ResourceList.Rcs)
2023/09/30 22:31:49 Progress: 18/100 (ResourceList.Rcs)
2023/09/30 22:31:49 Progress: 19/100 (ResourceList.Rcs)
2023/09/30 22:31:49 Progress: 19/100 (ResourceList.Rcs)
2023/09/30 22:31:49 Progress: 20/100 (ResourceList.Rcs)
2023/09/30 22:31:49 Progress: 20/100 (ResourceList.Rcs)
2023/09/30 22:31:49 Progress: 20/100 (ResourceList.Rcs)
2023/09/30 22:31:49 Progress: 21/100 (ResourceList.Rcs)
2023/09/30 22:31:49 Progress: 21/100 (ResourceList.Rcs)
2023/09/30 22:31:49 Progress: 21/100 (ResourceList.Rcs)
2023/09/30 22:31:49 Progress: 22/100 (ResourceList.Rcs)
2023/09/30 22:31:49 Progress: 22/100 (ResourceList.Rcs)
2023/09/30 22:31:49 Progress: 22/100 (ResourceList.Rcs)
2023/09/30 22:31:49 Progress: 23/100 (ResourceList.Rcs)
2023/09/30 22:31:49 Progress: 23/100 (ResourceList.Rcs)
2023/09/30 22:31:49 Progress: 23/100 (ResourceList.Rcs)
2023/09/30 22:31:49 Progress: 24/100 (ResourceList.Rcs)
2023/09/30 22:31:49 Progress: 24/100 (ResourceList.Rcs)
2023/09/30 22:31:49 Progress: 24/100 (ResourceList.Rcs)
2023/09/30 22:31:49 Progress: 25/100 (ResourceList.Rcs)
2023/09/30 22:31:49 Progress: 25/100 (ResourceList.Rcs)
2023/09/30 22:31:49 Progress: 25/100 (ResourceList.Rcs)
2023/09/30 22:31:49 Progress: 26/100 (ResourceList.Rcs)
2023/09/30 22:31:49 Progress: 26/100 (ResourceList.Rcs)
2023/09/30 22:31:49 Progress: 26/100 (ResourceList.Rcs)
2023/09/30 22:31:49 Progress: 27/100 (ResourceList.Rcs)
2023/09/30 22:31:49 Progress: 27/100 (ResourceList.Rcs)
2023/09/30 22:31:49 Progress: 27/100 (ResourceList.Rcs)
2023/09/30 22:31:49 Progress: 28/100 (ResourceList.Rcs)
2023/09/30 22:31:49 Progress: 28/100 (ResourceList.Rcs)
2023/09/30 22:31:49 Progress: 28/100 (ResourceList.Rcs)
2023/09/30 22:31:49 Progress: 29/100 (ResourceList.Rcs)
2023/09/30 22:31:49 Progress: 29/100 (ResourceList.Rcs)
2023/09/30 22:31:49 Progress: 30/100 (ResourceList.Rcs)
2023/09/30 22:31:49 Progress: 30/100 (ResourceList.Rcs)
2023/09/30 22:31:49 Progress: 30/100 (ResourceList.Rcs)
2023/09/30 22:31:49 Progress: 31/100 (ResourceList.Rcs)
2023/09/30 22:31:49 Progress: 31/100 (ResourceList.Rcs)
2023/09/30 22:31:49 Progress: 31/100 (ResourceList.Rcs)
2023/09/30 22:31:49 Progress: 32/100 (ResourceList.Rcs)
2023/09/30 22:31:49 Progress: 32/100 (ResourceList.Rcs)
2023/09/30 22:31:49 Progress: 32/100 (ResourceList.Rcs)
2023/09/30 22:31:49 Progress: 33/100 (ResourceList.Rcs)

2023/09/30 22:31:49 Progress: 33/100 (ResourceList.Rcs)
2023/09/30 22:31:49 Progress: 33/100 (ResourceList.Rcs)
2023/09/30 22:31:49 Progress: 34/100 (ResourceList.Rcs)
2023/09/30 22:31:49 Progress: 34/100 (ResourceList.Rcs)
2023/09/30 22:31:49 Progress: 34/100 (ResourceList.Rcs)
2023/09/30 22:31:49 Progress: 35/100 (ResourceList.Rcs)
2023/09/30 22:31:49 Progress: 35/100 (ResourceList.Rcs)
2023/09/30 22:31:49 Progress: 35/100 (ResourceList.Rcs)
2023/09/30 22:31:49 Progress: 36/100 (ResourceList.Rcs)
2023/09/30 22:31:49 Progress: 36/100 (ResourceList.Rcs)
2023/09/30 22:31:49 Progress: 36/100 (ResourceList.Rcs)
2023/09/30 22:31:49 Progress: 37/100 (ResourceList.Rcs)
2023/09/30 22:31:49 Progress: 37/100 (ResourceList.Rcs)
2023/09/30 22:31:49 Progress: 37/100 (ResourceList.Rcs)
2023/09/30 22:31:49 Progress: 38/100 (ResourceList.Rcs)
2023/09/30 22:31:49 Progress: 38/100 (ResourceList.Rcs)
2023/09/30 22:31:49 Progress: 38/100 (ResourceList.Rcs)
2023/09/30 22:31:49 Progress: 39/100 (ResourceList.Rcs)
2023/09/30 22:31:49 Progress: 39/100 (ResourceList.Rcs)
2023/09/30 22:31:49 Progress: 40/100 (ResourceList.Rcs)
2023/09/30 22:31:49 Progress: 40/100 (ResourceList.Rcs)
2023/09/30 22:31:49 Progress: 40/100 (ResourceList.Rcs)
2023/09/30 22:31:49 Progress: 41/100 (ResourceList.Rcs)
2023/09/30 22:31:49 Progress: 41/100 (ResourceList.Rcs)
2023/09/30 22:31:49 Progress: 41/100 (ResourceList.Rcs)
2023/09/30 22:31:49 Progress: 42/100 (ResourceList.Rcs)
2023/09/30 22:31:49 Progress: 42/100 (ResourceList.Rcs)
2023/09/30 22:31:49 Progress: 42/100 (ResourceList.Rcs)
2023/09/30 22:31:49 Progress: 43/100 (ResourceList.Rcs)
2023/09/30 22:31:49 Progress: 43/100 (ResourceList.Rcs)
2023/09/30 22:31:49 Progress: 43/100 (ResourceList.Rcs)
2023/09/30 22:31:49 Progress: 44/100 (ResourceList.Rcs)
2023/09/30 22:31:49 Progress: 44/100 (ResourceList.Rcs)
2023/09/30 22:31:49 Progress: 44/100 (ResourceList.Rcs)
2023/09/30 22:31:49 Progress: 45/100 (ResourceList.Rcs)
2023/09/30 22:31:49 Progress: 45/100 (ResourceList.Rcs)
2023/09/30 22:31:49 Progress: 45/100 (ResourceList.Rcs)
2023/09/30 22:31:49 Progress: 46/100 (ResourceList.Rcs)
2023/09/30 22:31:49 Progress: 46/100 (ResourceList.Rcs)
2023/09/30 22:31:49 Progress: 46/100 (ResourceList.Rcs)
2023/09/30 22:31:49 Progress: 47/100 (ResourceList.Rcs)
2023/09/30 22:31:49 Progress: 47/100 (ResourceList.Rcs)
2023/09/30 22:31:49 Progress: 47/100 (ResourceList.Rcs)
2023/09/30 22:31:49 Progress: 48/100 (ResourceList.Rcs)
2023/09/30 22:31:49 Progress: 48/100 (ResourceList.Rcs)
2023/09/30 22:31:49 Progress: 48/100 (ResourceList.Rcs)
2023/09/30 22:31:49 Progress: 49/100 (ResourceList.Rcs)
2023/09/30 22:31:49 Progress: 49/100 (ResourceList.Rcs)
2023/09/30 22:31:49 Progress: 50/100 (ResourceList.Rcs)
2023/09/30 22:31:49 Progress: 50/100 (ResourceList.Rcs)
2023/09/30 22:31:49 Progress: 50/100 (ResourceList.Rcs)
2023/09/30 22:31:49 Progress: 51/100 (ResourceList.Rcs)
2023/09/30 22:31:49 Progress: 51/100 (ResourceList.Rcs)
2023/09/30 22:31:49 Progress: 51/100 (ResourceList.Rcs)
2023/09/30 22:31:49 Progress: 52/100 (ResourceList.Rcs)
2023/09/30 22:31:49 Progress: 52/100 (ResourceList.Rcs)
2023/09/30 22:31:49 Progress: 52/100 (ResourceList.Rcs)
2023/09/30 22:31:49 Progress: 53/100 (ResourceList.Rcs)
2023/09/30 22:31:49 Progress: 53/100 (ResourceList.Rcs)
2023/09/30 22:31:49 Progress: 53/100 (ResourceList.Rcs)
2023/09/30 22:31:49 Progress: 54/100 (ResourceList.Rcs)
2023/09/30 22:31:49 Progress: 54/100 (ResourceList.Rcs)
2023/09/30 22:31:49 Progress: 54/100 (ResourceList.Rcs)
2023/09/30 22:31:49 Progress: 55/100 (ResourceList.Rcs)
2023/09/30 22:31:49 Progress: 55/100 (ResourceList.Rcs)
2023/09/30 22:31:49 Progress: 55/100 (ResourceList.Rcs)
2023/09/30 22:31:49 Progress: 56/100 (ResourceList.Rcs)
2023/09/30 22:31:49 Progress: 56/100 (ResourceList.Rcs)
2023/09/30 22:31:49 Progress: 56/100 (ResourceList.Rcs)
2023/09/30 22:31:49 Progress: 57/100 (ResourceList.Rcs)
2023/09/30 22:31:49 Progress: 57/100 (ResourceList.Rcs)
2023/09/30 22:31:49 Progress: 57/100 (ResourceList.Rcs)
2023/09/30 22:31:49 Progress: 58/100 (ResourceList.Rcs)
2023/09/30 22:31:49 Progress: 58/100 (ResourceList.Rcs)
2023/09/30 22:31:49 Progress: 58/100 (ResourceList.Rcs)
2023/09/30 22:31:49 Progress: 59/100 (ResourceList.Rcs)
2023/09/30 22:31:49 Progress: 59/100 (ResourceList.Rcs)
2023/09/30 22:31:49 Progress: 60/100 (ResourceList.Rcs)
2023/09/30 22:31:49 Progress: 60/100 (ResourceList.Rcs)
2023/09/30 22:31:49 Progress: 60/100 (ResourceList.Rcs)
2023/09/30 22:31:49 Progress: 61/100 (ResourceList.Rcs)
2023/09/30 22:31:49 Progress: 61/100 (ResourceList.Rcs)
2023/09/30 22:31:49 Progress: 61/100 (ResourceList.Rcs)
2023/09/30 22:31:49 Progress: 62/100 (ResourceList.Rcs)
2023/09/30 22:31:49 Progress: 62/100 (ResourceList.Rcs)
2023/09/30 22:31:49 Progress: 62/100 (ResourceList.Rcs)
2023/09/30 22:31:49 Progress: 63/100 (ResourceList.Rcs)
2023/09/30 22:31:49 Progress: 63/100 (ResourceList.Rcs)
2023/09/30 22:31:49 Progress: 63/100 (ResourceList.Rcs)
2023/09/30 22:31:49 Progress: 64/100 (ResourceList.Rcs)
2023/09/30 22:31:49 Progress: 64/100 (ResourceList.Rcs)
2023/09/30 22:31:49 Progress: 64/100 (ResourceList.Rcs)
2023/09/30 22:31:49 Progress: 65/100 (ResourceList.Rcs)
2023/09/30 22:31:49 Progress: 65/100 (ResourceList.Rcs)
2023/09/30 22:31:49 Progress: 65/100 (ResourceList.Rcs)
2023/09/30 22:31:49 Progress: 66/100 (ResourceList.Rcs)
2023/09/30 22:31:49 Progress: 66/100 (ResourceList.Rcs)
2023/09/30 22:31:49 Progress: 66/100 (ResourceList.Rcs)
2023/09/30 22:31:49 Progress: 67/100 (ResourceList.Rcs)
2023/09/30 22:31:49 Progress: 67/100 (ResourceList.Rcs)
2023/09/30 22:31:49 Progress: 67/100 (ResourceList.Rcs)
2023/09/30 22:31:49 Progress: 68/100 (ResourceList.Rcs)
2023/09/30 22:31:49 Progress: 68/100 (ResourceList.Rcs)
2023/09/30 22:31:49 Progress: 68/100 (ResourceList.Rcs)
2023/09/30 22:31:49 Progress: 69/100 (ResourceList.Rcs)
2023/09/30 22:31:49 Progress: 69/100 (ResourceList.Rcs)
2023/09/30 22:31:49 Progress: 70/100 (ResourceList.Rcs)
2023/09/30 22:31:49 Progress: 70/100 (ResourceList.Rcs)
2023/09/30 22:31:49 Progress: 70/100 (ResourceList.Rcs)
2023/09/30 22:31:49 Progress: 71/100 (ResourceList.Rcs)
2023/09/30 22:31:49 Progress: 71/100 (ResourceList.Rcs)
2023/09/30 22:31:49 Progress: 71/100 (ResourceList.Rcs)
2023/09/30 22:31:49 Progress: 72/100 (ResourceList.Rcs)
2023/09/30 22:31:49 Progress: 72/100 (ResourceList.Rcs)
2023/09/30 22:31:49 Progress: 72/100 (ResourceList.Rcs)
2023/09/30 22:31:49 Progress: 73/100 (ResourceList.Rcs)
2023/09/30 22:31:49 Progress: 73/100 (ResourceList.Rcs)
2023/09/30 22:31:49 Progress: 73/100 (ResourceList.Rcs)
2023/09/30 22:31:49 Progress: 74/100 (ResourceList.Rcs)
2023/09/30 22:31:49 Progress: 74/100 (ResourceList.Rcs)
2023/09/30 22:31:49 Progress: 74/100 (ResourceList.Rcs)
2023/09/30 22:31:49 Progress: 75/100 (ResourceList.Rcs)
2023/09/30 22:31:49 Progress: 75/100 (ResourceList.Rcs)
2023/09/30 22:31:49 Progress: 75/100 (ResourceList.Rcs)
2023/09/30 22:31:49 Progress: 76/100 (ResourceList.Rcs)
2023/09/30 22:31:49 Progress: 76/100 (ResourceList.Rcs)
2023/09/30 22:31:49 Progress: 76/100 (ResourceList.Rcs)
2023/09/30 22:31:49 Progress: 77/100 (ResourceList.Rcs)
2023/09/30 22:31:49 Progress: 77/100 (ResourceList.Rcs)
2023/09/30 22:31:49 Progress: 77/100 (ResourceList.Rcs)
2023/09/30 22:31:49 Progress: 78/100 (ResourceList.Rcs)
2023/09/30 22:31:49 Progress: 78/100 (ResourceList.Rcs)
2023/09/30 22:31:49 Progress: 78/100 (ResourceList.Rcs)
2023/09/30 22:31:49 Progress: 79/100 (ResourceList.Rcs)
2023/09/30 22:31:49 Progress: 79/100 (ResourceList.Rcs)
2023/09/30 22:31:49 Progress: 80/100 (ResourceList.Rcs)
2023/09/30 22:31:49 Progress: 80/100 (ResourceList.Rcs)
2023/09/30 22:31:49 Progress: 80/100 (ResourceList.Rcs)
2023/09/30 22:31:49 Progress: 81/100 (ResourceList.Rcs)
2023/09/30 22:31:49 Progress: 81/100 (ResourceList.Rcs)
2023/09/30 22:31:49 Progress: 81/100 (ResourceList.Rcs)
2023/09/30 22:31:49 Progress: 82/100 (ResourceList.Rcs)
2023/09/30 22:31:49 Progress: 82/100 (ResourceList.Rcs)
2023/09/30 22:31:49 Progress: 82/100 (ResourceList.Rcs)
2023/09/30 22:31:49 Progress: 83/100 (ResourceList.Rcs)
2023/09/30 22:31:49 Progress: 83/100 (ResourceList.Rcs)
2023/09/30 22:31:49 Progress: 83/100 (ResourceList.Rcs)
2023/09/30 22:31:49 Progress: 84/100 (ResourceList.Rcs)
2023/09/30 22:31:49 Progress: 84/100 (ResourceList.Rcs)
2023/09/30 22:31:49 Progress: 84/100 (ResourceList.Rcs)
2023/09/30 22:31:49 Progress: 85/100 (ResourceList.Rcs)
2023/09/30 22:31:49 Progress: 85/100 (ResourceList.Rcs)
2023/09/30 22:31:49 Progress: 85/100 (ResourceList.Rcs)
2023/09/30 22:31:49 Progress: 86/100 (ResourceList.Rcs)
2023/09/30 22:31:49 Progress: 86/100 (ResourceList.Rcs)
2023/09/30 22:31:49 Progress: 86/100 (ResourceList.Rcs)
2023/09/30 22:31:49 Progress: 87/100 (ResourceList.Rcs)
2023/09/30 22:31:49 Progress: 87/100 (ResourceList.Rcs)
2023/09/30 22:31:49 Progress: 87/100 (ResourceList.Rcs)
2023/09/30 22:31:49 Progress: 88/100 (ResourceList.Rcs)
2023/09/30 22:31:49 Progress: 88/100 (ResourceList.Rcs)
2023/09/30 22:31:49 Progress: 88/100 (ResourceList.Rcs)
2023/09/30 22:31:49 Progress: 89/100 (ResourceList.Rcs)
2023/09/30 22:31:49 Progress: 89/100 (ResourceList.Rcs)
2023/09/30 22:31:49 Progress: 90/100 (ResourceList.Rcs)
2023/09/30 22:31:49 Progress: 90/100 (ResourceList.Rcs)
2023/09/30 22:31:49 Progress: 90/100 (ResourceList.Rcs)
2023/09/30 22:31:49 Progress: 91/100 (ResourceList.Rcs)
2023/09/30 22:31:49 Progress: 91/100 (ResourceList.Rcs)
2023/09/30 22:31:49 Progress: 91/100 (ResourceList.Rcs)
2023/09/30 22:31:49 Progress: 92/100 (ResourceList.Rcs)
2023/09/30 22:31:49 Progress: 92/100 (ResourceList.Rcs)
2023/09/30 22:31:49 Progress: 92/100 (ResourceList.Rcs)
2023/09/30 22:31:49 Progress: 93/100 (ResourceList.Rcs)
2023/09/30 22:31:49 Progress: 93/100 (ResourceList.Rcs)
2023/09/30 22:31:49 Progress: 93/100 (ResourceList.Rcs)
2023/09/30 22:31:49 Progress: 94/100 (ResourceList.Rcs)
2023/09/30 22:31:49 Progress: 94/100 (ResourceList.Rcs)
2023/09/30 22:31:49 Progress: 94/100 (ResourceList.Rcs)
2023/09/30 22:31:49 Progress: 95/100 (ResourceList.Rcs)
2023/09/30 22:31:49 Progress: 95/100 (ResourceList.Rcs)
2023/09/30 22:31:49 Progress: 95/100 (ResourceList.Rcs)
2023/09/30 22:31:49 Progress: 96/100 (ResourceList.Rcs)
2023/09/30 22:31:49 Progress: 96/100 (ResourceList.Rcs)
2023/09/30 22:31:49 Progress: 96/100 (ResourceList.Rcs)
2023/09/30 22:31:49 Progress: 97/100 (ResourceList.Rcs)
2023/09/30 22:31:49 Progress: 97/100 (ResourceList.Rcs)
2023/09/30 22:31:49 Progress: 97/100 (ResourceList.Rcs)
2023/09/30 22:31:49 Progress: 98/100 (ResourceList.Rcs)
2023/09/30 22:31:49 Progress: 98/100 (ResourceList.Rcs)
2023/09/30 22:31:49 Progress: 98/100 (ResourceList.Rcs)
2023/09/30 22:31:49 Progress: 99/100 (ResourceList.Rcs)
2023/09/30 22:31:49 Progress: 99/100 (ResourceList.Rcs)
2023/09/30 22:31:49 Parsed 627 domain rules
2023/09/30 22:31:49 Parsed 18 IPv4 rules
2023/09/30 22:31:49 Parsed 520 DNS rules

2023/09/30 22:31:49 socket: connected to:  218.108.88.254:443
2023/09/30 22:31:49 tls: connected to:  218.108.88.254:443

2023/09/30 22:31:50 Login success, your IP: 10.190.69.66

2023/09/30 22:31:50 HTTP server listening on 127.0.0.1:1081
2023/09/30 22:31:50 SOCKS5 server listening on 127.0.0.1:1080

2023/09/30 22:31:50 socket: connected to:  218.108.88.254:443

panic: SOCKS5 listen failed: listen tcp 127.0.0.1:1080: bind: An attempt was made to access a socket in a way forbidden by its access permissions.

goroutine 161 [running]:
github.com/mythologyli/zju-connect/core.ServeSocks5(0xc0004ca000, {0xc000158104, 0x4, 0x7c}, {0xc00011c200, 0xe}, {0xb0c504, 0xa})
	github.com/mythologyli/zju-connect/core/socks.go:309 +0x754
github.com/mythologyli/zju-connect/core.(*EasyConnectClient).ServeSocks5(0x0?, {0xc00011c200?, 0x0?}, {0xb0c504?, 0x0?})
	github.com/mythologyli/zju-connect/core/EasyConnectClient.go:248 +0x45
created by github.com/mythologyli/zju-connect/core.StartClient in goroutine 1
	github.com/mythologyli/zju-connect/core/EasyConnectClient.go:159 +0x1185

panic: HTTP listen failed: listen tcp 127.0.0.1:1081: bind: An attempt was made to access a socket in a way forbidden by its access permissions.

goroutine 160 [running]:
github.com/mythologyli/zju-connect/core.ServeHttp({0xc00011c250, 0xe}, {0xc00011c200?, 0x0?}, {0x0?, 0x0?}, {0x0?, 0x0?})
	github.com/mythologyli/zju-connect/core/http.go:125 +0x279
github.com/mythologyli/zju-connect/core.(*EasyConnectClient).ServeHttp(0x0?, {0xc00011c250?, 0x0?}, {0xc00011c200?, 0x0?}, {0x0?, 0x0?}, {0x0?, 0x0?})
	github.com/mythologyli/zju-connect/core/EasyConnectClient.go:252 +0x45
created by github.com/mythologyli/zju-connect/core.StartClient in goroutine 1
	github.com/mythologyli/zju-connect/core/EasyConnectClient.go:142 +0xbec

2023-09-30 22:31:50 RVPN 断开！
```

**配置文件或启动参数** (请去除敏感信息)
```
最新版zju connect for windows
```

**Comment by Mythologyli** [comment]
把代理端口都换成高位端口试试

**Comment by Geniucker** [comment]
刚查了一下可能是动态端口的问题
![image](https://github.com/Mythologyli/zju-connect/assets/61449208/1ea147b2-374f-48a8-ac25-51c9db140e45)

**Comment by Geniucker** [comment]
换端口解决了
