### ISSUE TITLE
希望增加二次验证（动态口令）功能支持

### ISSUE THREAD

**Issue by ljyf5593** [Mythologyli/zju-connect#62]
**提交之前**

在提交报告之前，请确保：
+ 你正在使用 [Release](https://github.com/Mythologyli/zju-connect/releases) 中的最新版本
+ 如果你可以访问 CC98，请确保你已经阅读过以下说明：
    + [使用 ZJU Connect 代替 EasyConnect 提升你的 RVPN 体验](https://www.cc98.org/topic/5521873)
    + [端口转发、定时保活、自动选线、密码保存](https://www.cc98.org/topic/5570875)
+ 你已搜索过现有的 [Issues](https://github.com/Mythologyli/zju-connect/issues?q=is%3Aissue) 并且未发现重复

**确认无误后，请删除下方横线及以上内容。之后，请修改下方的模版并提交功能请求**

---

**软件版本**
v0.7.0

**使用环境**
Deepin 23

**服务端地址**
ccicvpn.iccec.cn:443

**功能请求描述** (建议结合图片说明)
希望可以增加二次验证（动态口令）功能支持
![image](https://github.com/user-attachments/assets/8f801467-8d06-439c-90a3-746d883096a2)

**Comment by Henry-ZHR** [comment]
试一下 #67

**Comment by Coldfengzi** [comment]
> > 这个动态口令是要怎么用的？是要填totp-secret = otpauth://totp/aaa?secret=XXXXX，还是直接填totp-secret = XXXXXXX。反正我两种都填了，都没能实现自动输入动态口令，不填的话也没出现动态口令框
> > ```
> > 2025/06/13 13:35:28 Start ZJU Connect v0.7.1
> > 2025/06/13 13:35:28 Exec func on initial: check tun mode cap
> > 2025/06/13 13:35:28 Exec func on initial  check tun mode cap success
> > 2025/06/13 13:35:28 Exec func on initial: check bind port
> > 2025/06/13 13:35:28 Exec func on initial  check bind port success
> > 2025/06/13 13:35:28 Request: https://vpn.XXXXXXXXXXXXXXXX.com:443/por/login_auth.csp?apiversion=1
> > 2025/06/13 13:35:28 TWFID: 56048a974272c041
> > 2025/06/13 13:35:28 RSA key: XXXXXXXXXXXXXXXXXXXXXX
> > 2025/06/13 13:35:28 RSA exp: 65537
> > 2025/06/13 13:35:28 CSRF Code: 1339664259
> > 2025/06/13 13:35:28 Request: https://vpn.XXXXXXXXXXXXXXXX:443/por/login_psw.csp?anti_replay=1&encrypt=1&type=cs
> > 2025/06/13 13:35:28 EasyConnect client setup error: Not implemented auth: <?xml version="1.0" encoding="utf-8"?>
> > <Auth>
> > 	<LBEnabled>0</LBEnabled>
> > 	<Message><![CDATA[password auth success]]></Message>
> > 	<Result>2</Result>
> > 	<CurAuth>1</CurAuth>
> > 	<NextAuth>4</NextAuth>
> > 	<ChallengeMsg><![CDATA[]]></ChallengeMsg>
> > 	<NextService>auth/hid</NextService>
> > 	<ErrorCode>1</ErrorCode>
> > 	<NextServiceSubType></NextServiceSubType>
> > 	<CSRF_RAND_CODE>1608434285</CSRF_RAND_CODE>
> > 	<EnableMAM>0</EnableMAM>
> > 	<AuthInfo><![CDATA[]]></AuthInfo>
> > 	<IsFirstAuth>1</IsFirstAuth>
> > </Auth>
> > ```
> 
> 请更新 zju-connect 的版本
```
2025/06/13 13:37:37 Start ZJU Connect v0.9.0
2025/06/13 13:37:37 Exec func on initial: check tun mode cap
2025/06/13 13:37:37 Exec func on initial  check tun mode cap success
2025/06/13 13:37:37 Exec func on initial: check bind port
2025/06/13 13:37:37 Exec func on initial  check bind port success
2025/06/13 13:37:37 Request: https://vpn.XXXXXXXXXXXXXXXX.com:443/por/login_auth.csp?apiversion=1
2025/06/13 13:37:37 VPN server version: M7.6.8R2
2025/06/13 13:37:37 TWFID: 15048add7375804c
2025/06/13 13:37:37 RSA key: XXXXXXXXXXXXXXXXXXXXXX
2025/06/13 13:37:37 RSA exp: 65537
2025/06/13 13:37:37 CSRF Code: 615037274
2025/06/13 13:37:37 Request: https://vpn.XXXXXXXXXXXXXXXX:443/por/login_psw.csp?anti_replay=1&encrypt=1&type=cs
2025/06/13 13:37:37 EasyConnect client setup error: Not implemented auth: <?xml version="1.0" encoding="utf-8"?>
<Auth>
	<LBEnabled>0</LBEnabled>
	<Message><![CDATA[password auth success]]></Message>
	<Result>2</Result>
	<CurAuth>1</CurAuth>
	<NextAuth>4</NextAuth>
	<ChallengeMsg><![CDATA[]]></ChallengeMsg>
	<NextService>auth/hid</NextService>
	<ErrorCode>1</ErrorCode>
	<NextServiceSubType></NextServiceSubType>
	<CSRF_RAND_CODE>1542392858</CSRF_RAND_CODE>
	<EnableMAM>0</EnableMAM>
	<AuthInfo><![CDATA[]]></AuthInfo>
	<IsFirstAuth>1</IsFirstAuth>
</Auth>
```
更新过一样的，所以退回老版本了。

**Comment by Mythologyli** [comment]
你这个下一步是 auth/hid，看着不像是 TOTP，请截图 EasyConnect 登录过程，敏感信息打码

**Comment by Coldfengzi** [comment]
![Image](https://github.com/user-attachments/assets/4fec095c-b966-47b9-a920-ac345dfc5202)我只有docker版的截图。是到这一步要输入二次验证码MFA

**Comment by Mythologyli** [comment]
https://github.com/Mythologyli/zju-connect/actions/runs/15627533822

尝试使用这个版本

**Comment by Coldfengzi** [comment]
> https://github.com/Mythologyli/zju-connect/actions/runs/15627533822
> 
> 尝试使用这个版本

```
替换上新版本，不管我输入多块，都提示超时：
2025/06/13 14:23:10 Start ZJU Connect v0.9.0
2025/06/13 14:23:10 Exec func on initial: check tun mode cap
2025/06/13 14:23:10 Exec func on initial  check tun mode cap success
2025/06/13 14:23:10 Exec func on initial: check bind port
2025/06/13 14:23:10 Exec func on initial  check bind port success
2025/06/13 14:23:10 Request: https://vpn.XXXXXXXXXXXXXXXX.com:443/por/login_auth.csp?apiversion=1
2025/06/13 14:23:10 VPN server version: M7.6.8R2
2025/06/13 14:23:10 TWFID: 49c0798b7deb4009
2025/06/13 14:23:10 RSA key: XXXXXXXXXXXXXXXXXXXXXX
2025/06/13 14:23:10 RSA exp: 65537
2025/06/13 14:23:10 CSRF Code: 1812931774
2025/06/13 14:23:10 Request: https://vpn.XXXXXXXXXXXXXXXX.com:443/por/login_psw.csp?anti_replay=1&encrypt=1&type=cs
2025/06/13 14:23:10 TOTP required
Please enter your TOTP code:887881
2025/06/13 14:23:11 TOTP Request: https://vpn.XXXXXXXXXXXXXXXX.com:443/por/login_token.csp
goroutine 1 [running]:
runtime/debug.Stack()
	runtime/debug/stack.go:26 +0x5e
runtime/debug.PrintStack()
	runtime/debug/stack.go:18 +0x13
github.com/mythologyli/zju-connect/client.(*EasyConnectClient).loginTOTP(0xc000156180)
	github.com/mythologyli/zju-connect/client/request.go:302 +0x912
github.com/mythologyli/zju-connect/client.(*EasyConnectClient).requestTwfID(0xc000156180)
	github.com/mythologyli/zju-connect/client/request.go:41 +0x8e
github.com/mythologyli/zju-connect/client.(*EasyConnectClient).Setup(0xc000156180)
	github.com/mythologyli/zju-connect/client/client.go:123 +0x27
main.main()
	github.com/mythologyli/zju-connect/main.go:77 +0x6c7
2025/06/13 14:23:11 EasyConnect client setup error: TOTP verification failed: <?xml version="1.0" encoding="utf-8"?>
<Auth>
	<LBEnabled>0</LBEnabled>
	<CSRF_RAND_CODE>743769354</CSRF_RAND_CODE>
	<AuthInfo><![CDATA[]]></AuthInfo>
	<Note><![CDATA[User has not logged in yet or timed out!]]></Note>
	<ErrorCode>20026</ErrorCode>
	<Result>0</Result>
	<Message><![CDATA[unexpected secondary auth]]></Message>
</Auth>
```

**Comment by Mythologyli** [comment]
看起来是在 totp 认证前有一步对用户隐藏的 hid 认证，我新开一个 issue 吧
